#!/bin/bash -e
# shellcheck source=meta-mitaccomputing/common/meta-common/recipes-mitac/plat-tool/files/mitac-common-functions
LIBPATH=/usr/libexec
source $LIBPATH/mitac-common-functions

BOOT_FAN_PWM=30
PLATFORM_ID='DEFAULT'
get_platform_id PLATFORM_ID
#PLATFORM_SHORT_ID=${PLATFORM_ID%%-*}
PLATFORM_SHORT_ID=${PLATFORM_ID::5}
PLATFORM_FULL_NAME="com.mitac.Hardware.Chassis.Model.$PLATFORM_ID"
PLATFORM_COMPACT_NAME="com.mitac.Hardware.Chassis.Model.$PLATFORM_SHORT_ID"
echo "$PLATFORM_FULL_NAME"

mkdir -p /usr/share/swampd/

if [ -d $LIBPATH/$PLATFORM_FULL_NAME ]; then
        echo "Use platform config from $LIBPATH/$PLATFORM_FULL_NAME"
        MAINBOARD_LIB=$LIBPATH/$PLATFORM_FULL_NAME/thermal-mgmt-init-functions
        if [ -f $MAINBOARD_LIB ]; then
                source $MAINBOARD_LIB
                echo "Call init-phosphor-pid-control"
                init-phosphor-pid-control
        else
                echo "Can't find thermal-mgmt-init-functions"
                exit 1
        fi

elif [ -d $LIBPATH/$PLATFORM_COMPACT_NAME ]; then
        echo "Use platform config from $LIBPATH/$PLATFORM_COMPACT_NAME"
        MAINBOARD_LIB=$LIBPATH/$PLATFORM_COMPACT_NAME/thermal-mgmt-init-functions
        if [ -f $MAINBOARD_LIB ]; then
                source $MAINBOARD_LIB
                echo "Call init-phosphor-pid-control"
                init-phosphor-pid-control
        else
                echo "Can't find thermal-mgmt-init-functions"
                exit 1
        fi
else
        set +e
        echo $BOOT_FAN_PWM > /sys/devices/platform/pwm-fan0/hwmon/hwmon1/pwm1
        echo $BOOT_FAN_PWM > /sys/devices/platform/pwm-fan1/hwmon/hwmon2/pwm1
        echo $BOOT_FAN_PWM > /sys/devices/platform/pwm-fan2/hwmon/hwmon3/pwm1
        echo $BOOT_FAN_PWM > /sys/devices/platform/pwm-fan3/hwmon/hwmon4/pwm1
        echo $BOOT_FAN_PWM > /sys/devices/platform/pwm-fan4/hwmon/hwmon5/pwm1
        echo $BOOT_FAN_PWM > /sys/devices/platform/pwm-fan5/hwmon/hwmon6/pwm1
        set -e
fi

exit 0
